extends: [
    'airbnb-base',
    'plugin:flowtype/recommended',
    "parser": "babel-eslint",
    'prettier'
  ]
env: {'jest': true }
plugins: [ 'prettier','flowtype' ]
globals: {
  'db': true,
  'tableNames': true
}
rules: {
  'prettier/prettier': [
    'error',
    {
      singleQuote: true,
      trailingComma: 'all',
      bracketSpacing: true,
      semi: true,
      parser: flow
    },
  ],
  semi: [0],
  no-param-reassign: [0],
  import/no-extraneous-dependencies: [0],
  import/extensions:[
    off,
    'never'],
  prefer-destructuring: ['error', {
      'VariableDeclarator': {
        'array': true,
        'object': true
      },
      'AssignmentExpression': {
        'array': true,
        'object': false
      }
    }, {
      'enforceForRenamedProperties': false
    }],
  }
